export const SET_TICKER_OPTIONS = "SET_TICKER_OPTIONS";
export const SET_SELECTED_EQUITY = "SET_SELECTED_EQUITY";
export const SET_TECHNICAL_INDICATOR = "SET_TECHNICAL_INDICATOR";
export const SET_TIMESCALE = "SET_TIMESCALE";
export const SET_INTRADAY_WEBSOCKET = "SET_INTRADAY_WEBSOCKET";

export const timeScaleValues: string[] = ['1D', '1W', '1M', '1Y']